# Generated by Django 3.1.3 on 2022-03-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create',
            new_name='create_date',
        ),
    ]
